### ISSUE TITLE
ableton live

### ISSUE THREAD

**Issue by matthieu-vitse-sciviz** [ThatGuySam/doesitarm#13] opened 2020-11-11 10:50 UTC

**Comment by ThatGuySam** [comment] 2020-11-11 16:52
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment] 2020-11-12 01:48
Looks like this forum is saying it’s not ready yet 
https://forum.ableton.com/viewtopic.php?t=240993

Download Link
https://www.ableton.com/en/trial/

**Comment by ThatGuySam** [comment] 2020-11-12 18:33
From @photovirus via #71

> **The official name of the app**
> Ableton Live
> 
> **Proposed App Status**
> ✳️ Can run well enough via Rosetta or some other caveat
> 
> **Related Issue Tracker Link or discussion**
> https://forum.ableton.com/viewtopic.php?f=1&t=240993&p=1783349&hilit=apple+silicon#p1783349
> 
> **An Official App Download Link**
> https://ableton.com
> 
> **Additional context**
> Press release of one of the plugins states they've run their plugin in Ableton without issues: https://neuraldsp.com/blogs/news/macos-big-sur-and-apple-silicon-compatibility
> Which means they've got Ableton itself running on Apple Silicon

**Comment by frictionlessDevelopments** [comment] 2020-11-19 18:31
duplicate of #156

**Comment by ThatGuySam** [comment] 2020-11-19 18:38
App is now live on the site! 

https://doesitarm.com/app/ableton/

Feel free to browse through the other issues to help with missing info on other apps.

**Closed by ThatGuySam** 2020-11-19 18:38 UTC
Labels: Needs Rosetta Testing
