### ISSUE TITLE
NTSF for Mac

### ISSUE THREAD

**Issue by Kurville** [ThatGuySam/doesitarm#482] opened 2020-12-30 04:44 UTC
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{NTSF for Mac}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{Full Native Support (universal build)}

**Proposed App Category**
{Utility}

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**
{https://www.paragon-software.com/home/ntfs-mac/ }
{Seagate OEM version https://www.seagate.com/ca/en/support/software/paragon/#downloads }

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by raphaelgurtner** [comment] 2020-12-30 06:25
Duplicate of #354

**Comment by ThatGuySam** [comment] 2021-01-07 18:11
@raphaelgurtner Good catch! We'll close this in favor of #354

**Closed by ThatGuySam** 2021-01-07 18:11 UTC
Labels: New App Request

**Comment by ThatGuySam** [comment] 2021-01-07 21:42
App is now live on the site! 

https://doesitarm.com/app/paragon-ntfs/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
