### ISSUE TITLE
git

### ISSUE THREAD

**Issue by shutter-cp** [ThatGuySam/doesitarm#216] opened 2020-11-18 23:48 UTC

**Comment by pawelostr** [comment] 2020-11-19 08:32
Duplicate of #54

**Comment by shaohua-yuan** [comment] 2020-11-19 15:03
git command, mysql command

**Comment by ThatGuySam** [comment] 2020-11-19 19:27
Thanks for the App Request! 

I'm closing this in favor of #54 which is ready to add

**Closed by ThatGuySam** 2020-11-19 19:27 UTC
Labels: New App Request
