### ISSUE TITLE
Notability for Mac

### ISSUE THREAD

**Issue by xanekka** [ThatGuySam/doesitarm#235] opened 2020-11-19 16:28 UTC

**Comment by ThatGuySam** [comment] 2020-11-19 19:50
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by raphaelgurtner** [comment] 2021-01-08 15:58
duplicate of #417 and already [live](https://doesitarm.com/app/notability/)

**Comment by ThatGuySam** [comment] 2021-01-09 14:43
@raphaelgurtner Good catch! 

Closing this issue now. 

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Closed by ThatGuySam** 2021-01-09 14:43 UTC
Labels: Needs Download Link, Needs Reported Status, Needs Tracker Link, New App Request
