### ISSUE TITLE
Update on Spotify Support

### ISSUE THREAD

**Issue by Kreller99** [ThatGuySam/doesitarm#196] opened 2020-11-18 12:09 UTC
Spotify app works on Mac Silicon

**Comment by Calinou** [comment] 2020-11-18 14:03
Duplicate of #172.

**Comment by ThatGuySam** [comment] 2020-11-18 17:18
Update is live on the site! 

https://doesitarm.com/app/spotify/

Feel free to browse through the other issues to help with missing info on other apps.

**Closed by ThatGuySam** 2020-11-18 17:18 UTC
